# 실습1 - 서울의 일교차

In [5]:
# 서울에서 일교차가 가장 큰 날, 최저 기온이 가장 낮은 날, 최고 기온이 가장 높은 날을 찾아 출력하시오
import csv
f = open('seoul.csv')
data = csv.reader(f)
header = next(data) #header 건너띄기 위함

#일교차 : 최고 - 최저 (row[4] - row[3])
#최저 기온 : row[3]
#최고 기온 : row[4]

max_dif = 0
min_low = 999
max_high = 0
date = ['']*3

for row in data:
    for i in range(2,5):
        dif = float(row[4]) - float(row[3])
        low = float(row[3])
        high = float(row[4])
        
        if dif > max_dif:
            max_dif = dif
            date[0] = row[0]
        if high > max_high:
            max_high = high
            date[1] = row[0]
        if low < min_low:
            min_low = low
            date[2] = row[0]
        
print("일교차가 가장 큰 날 : ", date[0])
print("최저기온이 가장 낮은 날 : ", date[2])
print("최고기온이 가장 높은 날 : ", date[1])

일교차가 가장 큰 날 :  2021-04-21
최저기온이 가장 낮은 날 :  2021-05-02
최고기온이 가장 높은 날 :  2021-05-14

# 실습2 - 지하철 이용객

In [1]:
#노선별로 가장 이용객이 많은 3개역, 가장 적은 3개 역 
#이용객 : 승차+하차
import csv
import re
import operator
f = open('subwayUsers2.csv','r',encoding = "utf-8")
data = csv.reader(f)
next(data)

def removeComma(a):
    char = a #940,925 > 940925로 변경
    p = re.compile("[^,]")
    a = "".join(p.findall(char))
    a = int(a)
    return a

dic = dict()
for row in data:
    subway = [row[3],removeComma(row[4])+removeComma(row[5])]
    if row[1] in dic:
        dic[row[1]].append(subway)
    else:
        dic[row[1]] = [subway]


for key,value in dic.items():
    print("========="+key+"==========")
    value = sorted(value, key = lambda x : x[1])
    #print(value)
    print("@ 이용객이 가장 많은 역 순위 @")
    for i in range(-1,-4,-1):
        print(value[i][0],value[i][1])
    print("@ 이용객이 가장 적은 역 순위 @")
    for i in range(0,3):
        print(value[i][0],value[i][1])

=========1호선==========
@ 이용객이 가장 많은 역 순위 @
서울역 1639892
종각 1309829
종로3가 943527
@ 이용객이 가장 적은 역 순위 @
동묘앞 423253
동대문 504353
신설동 613813
=========2호선==========
@ 이용객이 가장 많은 역 순위 @
강남 3167883
신림 2799927
잠실(송파구청) 2669433
@ 이용객이 가장 적은 역 순위 @
도림천 61915
신답 72623
용두(동대문구청) 107339
=========3호선==========
@ 이용객이 가장 많은 역 순위 @
고속터미널 1746144
양재(서초구청) 1639852
연신내 1630047
@ 이용객이 가장 적은 역 순위 @
충무로 15
학여울 71817
지축 139794
=========4호선==========
@ 이용객이 가장 많은 역 순위 @
수유(강북구청) 1538536
쌍문 1282986
미아사거리 1241073
@ 이용객이 가장 적은 역 순위 @
남태령 44147
동작(현충원) 105936
삼각지 197383
=========경부선==========
@ 이용객이 가장 많은 역 순위 @
영등포 1712414
수원 1500489
용산 1341463
@ 이용객이 가장 적은 역 순위 @
직산 32147
서동탄 58953
진위 64272
=========경인선==========
@ 이용객이 가장 많은 역 순위 @
부천 1495296
부평 1346383
역곡 1197906
@ 이용객이 가장 적은 역 순위 @
인천 127544
도원 131234
도화 170148
=========경원선==========
@ 이용객이 가장 많은 역 순위 @
의정부 814899
청량리(서울시립대입구) 639694
왕십리(성동구청) 614608
@ 이용객이 가장 적은 역 순위 @
창동 6
옥수 1787
보산 69877
=========안산선==========
@ 이용객이 가장 많은 역 순위 @
상록수 727908
중앙 714234
산본 698124
@ 이용객이 가장 적은 역 순위 @
신길온천 71231
수리산 171290
반월 186228
=========과천선==========
@ 이용객이 가장 많은 역 순위 @
범계 1058533
인덕원 1019046
평촌 742345
@ 이용객이 가장 적은 역 순위 @
경마공원 53458
대공원 91434
과천 209914
=========분당선==========
@ 이용객이 가장 많은 역 순위 @
야탑 1100531
서현 1023453
모란 909151
@ 이용객이 가장 적은 역 순위 @
복정 8
구룡 69748
보정 90014
=========일산선==========
@ 이용객이 가장 많은 역 순위 @
삼송 774332
화정 725658
대화 500508
@ 이용객이 가장 적은 역 순위 @
지축 4
대곡 65102
정발산 296070
=========중앙선==========
@ 이용객이 가장 많은 역 순위 @
회기 1001485
구리 585146
도농 400570
@ 이용객이 가장 적은 역 순위 @
지평 1705
신원 8310
오빈 11526
=========장항선==========
@ 이용객이 가장 많은 역 순위 @
온양온천 161235
아산 118077
쌍용(나사렛대) 81797
@ 이용객이 가장 적은 역 순위 @
배방 42895
신창(순천향대) 52073
봉명 52802
=========경의선==========
@ 이용객이 가장 많은 역 순위 @
일산 381097
행신 321438
탄현 308088
@ 이용객이 가장 적은 역 순위 @
계양 2
임진강 668
곡산 23554
=========경춘선==========
@ 이용객이 가장 많은 역 순위 @
평내호평 248617
마석 162475
퇴계원 152076
@ 이용객이 가장 적은 역 순위 @
굴봉산 4560
백양리 6045
김유정 10674
=========수인선==========
@ 이용객이 가장 많은 역 순위 @
인천논현 241320
인하대 241139
소래포구 206516
@ 이용객이 가장 적은 역 순위 @
달월 3544
야목 7747
어천 24637
=========경강선==========
@ 이용객이 가장 많은 역 순위 @
경기광주 284699
판교 179677
초월 124634
@ 이용객이 가장 적은 역 순위 @
세종대왕릉 11017
이매 39721
신둔도예촌 48243
=========5호선==========
@ 이용객이 가장 많은 역 순위 @
까치산 1268756
광화문(세종문화회관) 1218113
화곡 1213929
@ 이용객이 가장 적은 역 순위 @
동대문역사문화공원(DDP) 129478
오금 157683
올림픽공원(한국체대) 160965
=========6호선==========
@ 이용객이 가장 많은 역 순위 @
응암 783532
공덕 740299
망원 620819
@ 이용객이 가장 적은 역 순위 @
신내 3
연신내 9
버티고개 95433
=========7호선==========
@ 이용객이 가장 많은 역 순위 @
가산디지털단지 1964995
학동 1045919
광명사거리 1031881
@ 이용객이 가장 적은 역 순위 @
장암 71882
부천종합운동장 189806
삼산체육관 192403
=========8호선==========
@ 이용객이 가장 많은 역 순위 @
문정 920401
암사 792715
장지 755265
@ 이용객이 가장 적은 역 순위 @
모란 172775
신흥 216033
수진 223398
=========9호선==========
@ 이용객이 가장 많은 역 순위 @
신논현 1240544
노량진 1017044
여의도 891114
@ 이용객이 가장 적은 역 순위 @
동작(현충원) 64249
개화 92531
구반포 114269
=========공항철도 1호선==========
@ 이용객이 가장 많은 역 순위 @
디지털미디어시티 510128
계양 383313
김포공항 373367
@ 이용객이 가장 적은 역 순위 @
인천공항2터미널 97566
공덕 103008
공항화물청사 116016
=========9호선2~3단계==========
@ 이용객이 가장 많은 역 순위 @
봉은사 628382
언주 415847
선정릉 392464
@ 이용객이 가장 적은 역 순위 @
둔촌오륜 43922
한성백제 94698
종합운동장 169085
=========우이신설선==========
@ 이용객이 가장 많은 역 순위 @
북한산보국문 251118
솔샘 236299
정릉 188559
@ 이용객이 가장 적은 역 순위 @
보문 68519
삼양 95653
신설동 97960

# Class(기상청)

In [1]:
import csv
f = open('seoul.csv','r',encoding = "cp949")
data = csv.reader(f,delimiter=',') #파일 읽기
for row in data:
    print(row)
f.close()

['날짜', '지점', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)']
['2021-04-20', '108', '14.8', '8.1', '22']
['2021-04-21', '108', '19.1', '10.3', '28.2']
['2021-04-22', '108', '20.9', '16.1', '27.5']
['2021-04-23', '108', '19', '17', '21.7']
['2021-04-24', '108', '18.3', '15.3', '22.2']
['2021-04-25', '108', '18.2', '12.6', '24']
['2021-04-26', '108', '16.2', '12.3', '20.6']
['2021-04-27', '108', '15.4', '12.5', '20']
['2021-04-28', '108', '14.5', '11.2', '18.2']
['2021-04-29', '108', '14.6', '10.9', '20.1']
['2021-04-30', '108', '11.3', '8.6', '14.6']
['2021-05-01', '108', '10.2', '8.5', '15.3']
['2021-05-02', '108', '12.4', '7.3', '18.7']
['2021-05-03', '108', '14.1', '8.4', '20.3']
['2021-05-04', '108', '13.8', '11.4', '15.8']
['2021-05-05', '108', '13.9', '10.3', '18.4']
['2021-05-06', '108', '15.7', '7.9', '23.1']
['2021-05-07', '108', '14.4', '10.7', '17.2']
['2021-05-08', '108', '14.3', '8.9', '21']
['2021-05-09', '108', '15.7', '10', '21.8']
['2021-05-10', '108', '13.2', '11.7', '14.6']
['2021-05-11', '108', '18.5', '9.4', '25.7']
['2021-05-12', '108', '22', '16.9', '27.7']
['2021-05-13', '108', '22.9', '16.6', '29.6']
['2021-05-14', '108', '24.1', '18', '30.8']
['2021-05-15', '108', '22.1', '20.8', '26.2']
['2021-05-16', '108', '18.4', '14.8', '20.8']
['2021-05-17', '108', '15.3', '14.2', '16.7']
['2021-05-18', '108', '17.9', '13.6', '24.5']

In [2]:
#서울의 최고 기온이 가장 높았던 날은 언제였고, 몇 도였을까?
import csv
f = open('seoul.csv')
data = csv.reader(f)
header = next(data) #header 건너띄기 위함
max_temp= -999
max_data = ''
for row in data:
    if row[-1] == '': #최고 기온 데이터 누락 시
        row[-1] = -999
        
    row[-1] = float(row[-1])
    if max_temp < row[-1]:
        max_data = row[0]
        max_temp = row[-1]
f.close()
print('기상 관측 이래 서울의 최고 기온이 가장 높았던 날은', max_data+'로, ',max_temp,'도 였습니다.')

기상 관측 이래 서울의 최고 기온이 가장 높았던 날은 2021-05-14로,  30.8 도 였습니다.

# 수업 (대중교통)

In [17]:
#유임/무임 최대 비율
import csv
import re
f = open('subwayfee.csv','r',encoding = "utf-8")
data = csv.reader(f)
next(data)
mx = 0
rate = 0
for row in data:
    for i in range(4,8):
        char = row[i] #940,925 > 940925로 변경
        p = re.compile("[^,]")
        row[i] = "".join(p.findall(char))
        
        row[i] = int(row[i])
    if row[6] != 0:
        rate = row[4] / row[6]
        if rate > mx:
            mx = rate
print(mx)

34.0

In [18]:
#유임 승차 비율이 가장 높은 역
#유임/(유임+무임)
import csv
f = open('subwayfee.csv','r',encoding = "utf-8")
data = csv.reader(f)
next(data)

mx = 0
rate = 0
mx_station = ''

for row in data:
    for i in range(4,8):
        char = row[i] #940,925 > 940925로 변경
        p = re.compile("[^,]")
        row[i] = "".join(p.findall(char))
        
        row[i] = int(row[i])
        
    if (row[4]+row[6]) != 0:
        rate = row[4] / (row[4] + row[6])
        if rate > mx:
            mx = rate
            mx_station = row[3] + ' ' + row[1]
            
print(mx_station, round(mx * 100,2))

복정 분당선 100.0

In [19]:
#유무임 승하차 인원이 가장 많은 역
import csv
f = open('subwayfee.csv','r',encoding = "utf-8")
data = csv.reader(f)
next(data)

mx = [0]*4
mx_station = ['']*4
label = ['유임승차','유임하차','무임승차','무임하차']

for row in data:
    for i in range(4,8):
        char = row[i] #940,925 > 940925로 변경
        p = re.compile("[^,]")
        row[i] = "".join(p.findall(char))
        
        row[i] = int(row[i])
        if row[i] > mx[i-4]:
            mx[i-4] = row[i]
            mx_station[i-4] = row[3] + ' ' + row[1]
for i in range(4):
    print(label[i] + ' : ' + mx_station[i] , mx[i])

유임승차 : 강남 2호선 2003912
유임하차 : 강남 2호선 1986812
무임승차 : 종로3가 1호선 254584
무임하차 : 제기동 1호선 267958